mnylc/mnylc.github.io

pages/599studio.md, pages/vinyl.md
Example:
* Added x
* Removed y
Example: …
=> added content to 599studio.md, added vinyl.md

pages/board.md
=> Updated Board Info

pages/599studio.md, pages/vinyl.md
Example:
* Added x
* Removed y
Example: …
=> added to 599studio.md

_layouts/page.html
Example:
* Added x
* Removed y
Example: …
=> removed body class thing that wasn't working on gh-pages

_posts/news/2017-03-29-METRO-AND-XFR-COLLECTIVE-NEW-PARTNERSHIP.markdown, pages/join.md
Example:
* Added x
* Removed y
Example: …
=> content edits

pages/599studio.md
Example:
* Added x
* Removed y
Example: …
=> updated 599studio.md to include Margo's descriptions

_sass/_variables.scss, assets/css/agency.scss
@DiegoPino 
Change the accent color from pink to teal and background to white.
=> Color updates

pages/join.md
Removed the following sentence in the myMETRO section of this page:
“Benefits include scholarships to conferences of your choosing, access
to Lynda.com, our exclusive career services packages, and much more.”
=> Updated myMETRO Benefits

pages/projects/meetups.md
- Added Haruko, deleted Helen
- Changed description
=> Updated Library Instruction Meetup

pages/599studio.md
deleted MOTU audio interface from equipment list
deleted MOTU audio interface from equipment list because we didn't purchase it
shorter, updated list
No need to test
none
@jmignault
=> update audio equipment list 599studio.md

pages/staff.md
removed biographies for Caroline Catchpole and Susan Klimley
=> updated staff page

_posts/news/2017-06-06-new-website.markdown
added news post about our website
=> added news post

pages/staff.md
Molly added her bio
Example:
* Added x
* Removed y
Example:
* Does this change require any other modifications to be made …
=> added Molly's bio on staff.md

pages/staff.md
Added Library Bytegeist to Molly's bio
Make's Molly's bio more complete
not much
no need to test
none
@jmignault
=> update Molly's bio

pages/599studio.md
changed working to Reaper description
makes Reaper description more accurate
Added: Reaper is a DAW
no testing needed
none
@jmignault
=> changed working to Reaper description

pages/join.md
Example:
* Added x
* Removed y
Example: …
=> Updated Membership Dues Fees

pages/members.md
John, I'll be working on this list over the next few weeks. As membership invoices are mailed and returned (or not), there will be more changes/updates.
Example:
* Added x
* Removed y
Example:
* Does this change require …
=> Updated Institutional Members List

pages/members.md
Example:
* Added x
* Removed y
Example: …
=> Membership edit

_posts/news/2017-07-10-library-bytegeist-retrospective.markdown
added a couple links to episodes
added links to episodes
Links!
no testing needed
@jmignault
=> update Library Bytegeist retrospective

_posts/news/2017-07-10-library-bytegeist-retrospective.markdown
the link was missing a parenthesis
Example:
* Added x
* Removed y
Example:
* Does this change require any other …
=> fixed link to Library Retrospective

pages/staff.md
Example:
* Added x
* Removed y
Example: …
=> Adding Karen Hwang to the staff page

pages/join.md
=> updated / join

pages/services/599studio.md
We now have descriptions, forms, and documents explaining the transfer station studio services
Gives information and action items for people interested in using our transfer station sections
* a new section, #3, for the studio services about the AV Transfer Station
* Link added to AV Transfer form
* Description added of AV Transfer equipment
* Link added to description of equipment
* Link added to AV Transfer documentation and workflows
* make sure the external links and internal anchor link work
PLEASE DISREGARD THE LAST PULL REQUEST -- this pull request contains all in the changes. Sorry, I shouldn't have edited in this order, I just started to get panicked about updating everything last night.
@jmignault
=> Update AV Transfer Station section

pages/podcast.md
I tried to embed the iframes of the episodes from Soundcloud -- let's see if it works.
I included a description of Library Bytegeist and made the episodes available to play on our website.
* Added description of Library Bytegeist at the top of the page
* included link to Library Bytegeist twitter account
* Added Soundcloud iFrame embeds for episodes 1 - 14
* Try playing the podcast episodes from the website and see if it works
none
@jmignault
=> included Library Bytegeist description + episodes

pages/podcast.md
Fixed the width of the iframes for episodes 10 and 12, deleted episode descriptions, changed the headers from h4 to h3
Fixed the width of the iframes for episodes 10 and 12, deleted episode descriptions, changed the headers from h4 to h3
* Deleted all episode descriptions (it looked awkward)
* Changed the width of the iframe for episodes 10 and 12 (I missed them on the last round of edits)
* Changed the episode names from H4 to H3
*check to make sure everything looks right
I might need to experiment more with how to add episode descriptions and link transcripts
@jmignault
=> changed headers, episode description, iframe width

pages/services/599studio.md
Added a "book a session here" link to MM&R services because it's ready to go live
Adds "Book a session here" text with a link out to Planyo for the Media Migration & Recovery studio services
* One link in the top menu
* One link in the longer description
Make sure the links work. Thanks!
@jmignault
=> Added a "book a session here" link to MM&R service

pages/services/599studio.md
Added mobile kit Planyo link, insurance form, and documentation link
It adds all the necessary information for people to rent out the audio recording kit
Example:
* added link to mobile kit planyo page
* added list of equipment in the mobile kit
* added link to mobile kit insurance form
* added link to mobile kit documentatoin
* test all of the links
=> Added mobile kit

pages/services/599studio.md
added line break
Line break needed 
new line break
none
none
Tag (@ mention) interested parties
=> line break between audio station and kit

pages/staff.md
Updated my bio to reflect a title change.
=> ISSUE 93: Updated my biography
